import type { Category } from '../types/categoryType';
import type { Product } from '../types/productType';

export const productsExample: Product[] = [
    {
        id: '1',
        name: 'Roadster 2000',
        categoryId: 'Road Bike',
        article: 'road-2000',
        brand: 'SpeedX',
        price: 499,
        isActive: true,
        amount: 'unlimited',
        createdAt: new Date(2024, 11, 8),
        updatedAt: new Date(2024, 11, 8),
    },
    {
        id: '2',
        name: 'Mountain King',
        categoryId: 'Mountain Bike',
        article: 'mountain-king',
        brand: 'TrailBlazer',
        price: 799,
        isActive: true,
        amount: 'unlimited',
        createdAt: new Date(2024, 11, 8),
        updatedAt: new Date(2024, 11, 8),
    },
    {
        id: '3',
        name: 'City Cruiser',
        categoryId: 'City Bike',
        article: 'city-cruiser',
        brand: 'UrbanRide',
        price: 299,
        isActive: true,
        amount: 'unlimited',
        createdAt: new Date(2024, 11, 8),
        updatedAt: new Date(2024, 11, 8),
    },
    {
        id: '4',
        name: 'Speed Demon',
        categoryId: 'Road Bike',
        article: 'speed-demon',
        brand: 'Velocity',
        price: 1200,
        isActive: true,
        amount: 'unlimited',
        createdAt: new Date(2024, 11, 8),
        updatedAt: new Date(2024, 11, 8),
    },
    {
        id: '5',
        name: 'Trail Blazer',
        categoryId: 'Mountain Bike',
        article: 'asdasdasd',
        brand: 'AdventureCo',
        price: 650,
        isActive: false,
        amount: 'unlimited',
        createdAt: new Date(2024, 11, 8),
        updatedAt: new Date(2024, 11, 8),
    },
];

export const categoriesExample: Category[] = [
    {
        id: '1',
        name: 'Road Bikes',
        description: 'Lightweight bikes built for speed on paved roads.',
        slug: 'bla-bla',
        imageUrl: 'src/category-image',
        createdAt: new Date(2024, 11, 8),
        updatedAt: new Date(2024, 11, 8),
        isActive: false,
    },
    {
        id: '2',
        name: 'Mountain Bikes',
        description: 'Durable bikes designed for off-road trails.',
        slug: 'bla-bla',
        imageUrl: 'src/category-image',
        createdAt: new Date(2024, 11, 8),
        updatedAt: new Date(2024, 11, 8),
        isActive: false,
    },
    {
        id: '3',
        name: 'City Bikes',
        description: 'Comfortable bikes ideal for urban commuting.',
        slug: 'bla-bla',
        imageUrl: 'src/category-image',
        createdAt: new Date(2024, 11, 8),
        updatedAt: new Date(2024, 11, 8),
        isActive: false,
    },
    {
        id: '4',
        name: 'Hybrid Bikes',
        description: 'Versatile bikes suitable for both road and light trails.',
        slug: 'bla-bla',
        imageUrl: 'src/category-image',
        createdAt: new Date(2024, 11, 8),
        updatedAt: new Date(2024, 11, 8),
        isActive: false,
    },
    {
        id: '5',
        name: 'Electric Bikes',
        description: 'Bikes with electric assist for easier riding.',
        slug: 'bla-bla',
        imageUrl: 'src/category-image',
        createdAt: new Date(2024, 11, 8),
        updatedAt: new Date(2024, 11, 8),
        isActive: false,
    },
];
